const users = [
  // ===== IT (20) =====
  { name: "Aarav Patel", branch: "IT", username: "aaravpatel1", password: "123456", skills: ["JavaScript","React","MongoDB"], linkedin: "https://www.linkedin.com/in/aaravpatel1" },
  { name: "Riya Shah", branch: "IT", username: "riyashah2", password: "123456", skills: ["HTML","CSS","JavaScript"], linkedin: "https://www.linkedin.com/in/riyashah2" },
  { name: "Karan Mehta", branch: "IT", username: "karanmehta3", password: "123456", skills: ["Node.js","MongoDB","Express"], linkedin: "https://www.linkedin.com/in/karanmehta3" },
  { name: "Neha Joshi", branch: "IT", username: "nehajoshi4", password: "123456", skills: ["React","CSS","HTML"], linkedin: "https://www.linkedin.com/in/nehajoshi4" },
  { name: "Yash Desai", branch: "IT", username: "yashdesai5", password: "123456", skills: ["JavaScript","Node.js","MongoDB"], linkedin: "https://www.linkedin.com/in/yashdesai5" },
  { name: "Priya Trivedi", branch: "IT", username: "priyatrivedi6", password: "123456", skills: ["HTML","CSS","React"], linkedin: "https://www.linkedin.com/in/priyatrivedi6" },
  { name: "Harsh Patel", branch: "IT", username: "harshpatel7", password: "123456", skills: ["MongoDB","Express","Node.js"], linkedin: "https://www.linkedin.com/in/harshpatel7" },
  { name: "Ananya Shah", branch: "IT", username: "ananyashah8", password: "123456", skills: ["React","JavaScript","CSS"], linkedin: "https://www.linkedin.com/in/ananyashah8" },
  { name: "Tushar Mehta", branch: "IT", username: "tusharmehta9", password: "123456", skills: ["Node.js","MongoDB","HTML"], linkedin: "https://www.linkedin.com/in/tusharmehta9" },
  { name: "Sneha Joshi", branch: "IT", username: "snehajoshi10", password: "123456", skills: ["CSS","React","JavaScript"], linkedin: "https://www.linkedin.com/in/snehajoshi10" },
  { name: "Rahul Desai", branch: "IT", username: "rahuldesai11", password: "123456", skills: ["HTML","Node.js","MongoDB"], linkedin: "https://www.linkedin.com/in/rahuldesai11" },
  { name: "Ishita Patel", branch: "IT", username: "ishitapatel12", password: "123456", skills: ["React","CSS","JavaScript"], linkedin: "https://www.linkedin.com/in/ishitapatel12" },
  { name: "Manish Shah", branch: "IT", username: "manishshah13", password: "123456", skills: ["Node.js","Express","MongoDB"], linkedin: "https://www.linkedin.com/in/manishshah13" },
  { name: "Kavya Mehta", branch: "IT", username: "kavyamehta14", password: "123456", skills: ["HTML","CSS","React"], linkedin: "https://www.linkedin.com/in/kavyamehta14" },
  { name: "Deepak Joshi", branch: "IT", username: "deepakjoshi15", password: "123456", skills: ["JavaScript","MongoDB","Node.js"], linkedin: "https://www.linkedin.com/in/deepakjoshi15" },
  { name: "Rohan Desai", branch: "IT", username: "rohandeasi16", password: "123456", skills: ["React","CSS","HTML"], linkedin: "https://www.linkedin.com/in/rohandeasi16" },
  { name: "Pooja Patel", branch: "IT", username: "poojapatel17", password: "123456", skills: ["JavaScript","Node.js","Express"], linkedin: "https://www.linkedin.com/in/poojapatel17" },
  { name: "Amit Shah", branch: "IT", username: "amitshah18", password: "123456", skills: ["HTML","CSS","MongoDB"], linkedin: "https://www.linkedin.com/in/amitshah18" },
  { name: "Nikhil Mehta", branch: "IT", username: "nikhilmehta19", password: "123456", skills: ["React","Node.js","JavaScript"], linkedin: "https://www.linkedin.com/in/nikhilmehta19" },
  { name: "Yash Patel", branch: "IT", username: "yashpatel20", password: "123456", skills: ["MongoDB","Express","Node.js"], linkedin: "https://www.linkedin.com/in/yashpatel20" },

  // ===== ICT (20) =====
  { name: "Arjun Iyer", branch: "ICT", username: "arjuniyer21", password: "123456", skills: ["Python","Django","Linux"], linkedin: "https://www.linkedin.com/in/arjuniyer21" },
  { name: "Priya Verma", branch: "ICT", username: "priyaverma22", password: "123456", skills: ["Cyber Security","Networking","Linux"], linkedin: "https://www.linkedin.com/in/priyaverma22" },
  { name: "Vivaan Reddy", branch: "ICT", username: "vivaanreddy23", password: "123456", skills: ["Python","Django","Cyber Security"], linkedin: "https://www.linkedin.com/in/vivaanreddy23" },
  { name: "Kavya Nair", branch: "ICT", username: "kavyanair24", password: "123456", skills: ["Linux","Networking","Python"], linkedin: "https://www.linkedin.com/in/kavyanair24" },
  { name: "Rahul Iyer", branch: "ICT", username: "rahuliyer25", password: "123456", skills: ["Cyber Security","Django","Linux"], linkedin: "https://www.linkedin.com/in/rahuliyer25" },
  { name: "Sneha Reddy", branch: "ICT", username: "snehareddy26", password: "123456", skills: ["Python","Networking","Linux"], linkedin: "https://www.linkedin.com/in/snehareddy26" },
  { name: "Aditya Nair", branch: "ICT", username: "adityanair27", password: "123456", skills: ["Django","Python","Cyber Security"], linkedin: "https://www.linkedin.com/in/adityanair27" },
  { name: "Ananya Iyer", branch: "ICT", username: "ananyaiyer28", password: "123456", skills: ["Linux","Networking","Cyber Security"], linkedin: "https://www.linkedin.com/in/ananyaiyer28" },
  { name: "Tushar Reddy", branch: "ICT", username: "tusharreddy29", password: "123456", skills: ["Python","Django","Linux"], linkedin: "https://www.linkedin.com/in/tusharreddy29" },
  { name: "Neha Nair", branch: "ICT", username: "nehanair30", password: "123456", skills: ["Cyber Security","Networking","Python"], linkedin: "https://www.linkedin.com/in/nehanair30" },
  { name: "Manish Iyer", branch: "ICT", username: "manishiyer31", password: "123456", skills: ["Linux","Python","Django"], linkedin: "https://www.linkedin.com/in/manishiyer31" },
  { name: "Riya Reddy", branch: "ICT", username: "riyareddy32", password: "123456", skills: ["Cyber Security","Linux","Networking"], linkedin: "https://www.linkedin.com/in/riyareddy32" },
  { name: "Amit Nair", branch: "ICT", username: "amitnair33", password: "123456", skills: ["Python","Django","Linux"], linkedin: "https://www.linkedin.com/in/amitnair33" },
  { name: "Karan Iyer", branch: "ICT", username: "karaniyer34", password: "123456", skills: ["Cyber Security","Networking","Linux"], linkedin: "https://www.linkedin.com/in/karaniyer34" },
  { name: "Pooja Reddy", branch: "ICT", username: "poojareddy35", password: "123456", skills: ["Python","Linux","Django"], linkedin: "https://www.linkedin.com/in/poojareddy35" },
  { name: "Nikhil Nair", branch: "ICT", username: "nikhilnair36", password: "123456", skills: ["Networking","Cyber Security","Linux"], linkedin: "https://www.linkedin.com/in/nikhilnair36" },
  { name: "Harsh Iyer", branch: "ICT", username: "harshiyer37", password: "123456", skills: ["Python","Django","Cyber Security"], linkedin: "https://www.linkedin.com/in/harshiyer37" },
  { name: "Deepak Reddy", branch: "ICT", username: "deepakreddy38", password: "123456", skills: ["Linux","Networking","Python"], linkedin: "https://www.linkedin.com/in/deepakreddy38" },
  { name: "Yash Nair", branch: "ICT", username: "yashnair39", password: "123456", skills: ["Cyber Security","Django","Linux"], linkedin: "https://www.linkedin.com/in/yashnair39" },
  { name: "Ishita Iyer", branch: "ICT", username: "ishitaiyer40", password: "123456", skills: ["Python","Networking","Cyber Security"], linkedin: "https://www.linkedin.com/in/ishitaiyer40" },

  // ===== EC (20) =====
  { name: "Manish Gupta", branch: "EC", username: "manishgupta41", password: "123456", skills: ["Embedded Systems","Arduino","C"], linkedin: "https://www.linkedin.com/in/manishgupta41" },
  { name: "Suresh Joshi", branch: "EC", username: "sureshjoshi42", password: "123456", skills: ["VLSI","C","Microcontrollers"], linkedin: "https://www.linkedin.com/in/sureshjoshi42" },
  { name: "Aditya Patel", branch: "EC", username: "adityapatel43", password: "123456", skills: ["Arduino","Embedded Systems","VLSI"], linkedin: "https://www.linkedin.com/in/adityapatel43" },
  { name: "Karan Shah", branch: "EC", username: "karanshah44", password: "123456", skills: ["C","Microcontrollers","Arduino"], linkedin: "https://www.linkedin.com/in/karanshah44" },
  { name: "Yash Mehta", branch: "EC", username: "yashmehta45", password: "123456", skills: ["Embedded Systems","VLSI","C"], linkedin: "https://www.linkedin.com/in/yashmehta45" },
  { name: "Harsh Joshi", branch: "EC", username: "harshjoshi46", password: "123456", skills: ["Arduino","Microcontrollers","C"], linkedin: "https://www.linkedin.com/in/harshjoshi46" },
  { name: "Amit Patel", branch: "EC", username: "amitpatel47", password: "123456", skills: ["VLSI","Embedded Systems","Arduino"], linkedin: "https://www.linkedin.com/in/amitpatel47" },
  { name: "Nikhil Shah", branch: "EC", username: "nikhilshah48", password: "123456", skills: ["C","Arduino","Microcontrollers"], linkedin: "https://www.linkedin.com/in/nikhilshah48" },
  { name: "Rohan Mehta", branch: "EC", username: "rohanmehta49", password: "123456", skills: ["Embedded Systems","VLSI","C"], linkedin: "https://www.linkedin.com/in/rohanmehta49" },
  { name: "Deepak Joshi", branch: "EC", username: "deepakjoshi50", password: "123456", skills: ["Arduino","C","Microcontrollers"], linkedin: "https://www.linkedin.com/in/deepakjoshi50" },
  { name: "Kavya Patel", branch: "EC", username: "kavyapatel51", password: "123456", skills: ["VLSI","Embedded Systems","Arduino"], linkedin: "https://www.linkedin.com/in/kavyapatel51" },
  { name: "Ananya Shah", branch: "EC", username: "ananyashah52", password: "123456", skills: ["C","Microcontrollers","Arduino"], linkedin: "https://www.linkedin.com/in/ananyashah52" },
  { name: "Sneha Mehta", branch: "EC", username: "snehamehta53", password: "123456", skills: ["Embedded Systems","VLSI","C"], linkedin: "https://www.linkedin.com/in/snehamehta53" },
  { name: "Tushar Joshi", branch: "EC", username: "tusharjoshi54", password: "123456", skills: ["Arduino","Microcontrollers","C"], linkedin: "https://www.linkedin.com/in/tusharjoshi54" },
  { name: "Rahul Patel", branch: "EC", username: "rahulpatel55", password: "123456", skills: ["VLSI","Embedded Systems","Arduino"], linkedin: "https://www.linkedin.com/in/rahulpatel55" },
  { name: "Pooja Shah", branch: "EC", username: "poojashah56", password: "123456", skills: ["C","Arduino","Microcontrollers"], linkedin: "https://www.linkedin.com/in/poojashah56" },
  { name: "Ishita Mehta", branch: "EC", username: "ishitamehta57", password: "123456", skills: ["Embedded Systems","VLSI","C"], linkedin: "https://www.linkedin.com/in/ishitamehta57" },
  { name: "Yash Joshi", branch: "EC", username: "yashjoshi58", password: "123456", skills: ["Arduino","Microcontrollers","C"], linkedin: "https://www.linkedin.com/in/yashjoshi58" },
  { name: "Manish Patel", branch: "EC", username: "manishpatel59", password: "123456", skills: ["VLSI","Embedded Systems","Arduino"], linkedin: "https://www.linkedin.com/in/manishpatel59" },
  { name: "Kavya Shah", branch: "EC", username: "kavyashah60", password: "123456", skills: ["C","Microcontrollers","Arduino"], linkedin: "https://www.linkedin.com/in/kavyashah60" },

  // ===== EE (20) =====
  { name: "Sneha Sharma", branch: "EE", username: "snehasharma61", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/snehasharma61" },
  { name: "Rahul Verma", branch: "EE", username: "rahulverma62", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/rahulverma62" },
  { name: "Amit Gupta", branch: "EE", username: "amitgupta63", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/amitgupta63" },
  { name: "Pooja Sharma", branch: "EE", username: "poojasharma64", password: "123456", skills: ["Power Systems","Electrical Machines","MATLAB"], linkedin: "https://www.linkedin.com/in/poojasharma64" },
  { name: "Karan Verma", branch: "EE", username: "karanverma65", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/karanverma65" },
  { name: "Riya Gupta", branch: "EE", username: "riyagupta66", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/riyagupta66" },
  { name: "Neha Sharma", branch: "EE", username: "nehasharma67", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/nehasharma67" },
  { name: "Tushar Verma", branch: "EE", username: "tusharverma68", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/tusharverma68" },
  { name: "Deepak Gupta", branch: "EE", username: "deepakgupta69", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/deepakgupta69" },
  { name: "Ananya Sharma", branch: "EE", username: "ananyasharma70", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/ananyasharma70" },
  { name: "Yash Verma", branch: "EE", username: "yashverma71", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/yashverma71" },
  { name: "Kavya Gupta", branch: "EE", username: "kavyagupta72", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/kavyagupta72" },
  { name: "Manish Sharma", branch: "EE", username: "manishsharma73", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/manishsharma73" },
  { name: "Rohan Verma", branch: "EE", username: "rohanverma74", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/rohanverma74" },
  { name: "Ishita Gupta", branch: "EE", username: "ishitagupta75", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/ishitagupta75" },
  { name: "Harsh Sharma", branch: "EE", username: "harshsharma76", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/harshsharma76" },
  { name: "Nikhil Verma", branch: "EE", username: "nikhilverma77", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/nikhilverma77" },
  { name: "Pooja Gupta", branch: "EE", username: "poojagupta78", password: "123456", skills: ["Electrical Machines","MATLAB","Circuit Design"], linkedin: "https://www.linkedin.com/in/poojagupta78" },
  { name: "Aarav Sharma", branch: "EE", username: "aaravsharma79", password: "123456", skills: ["Power Systems","MATLAB","Electrical Machines"], linkedin: "https://www.linkedin.com/in/aaravsharma79" },
  { name: "Aditya Verma", branch: "EE", username: "adityaverma80", password: "123456", skills: ["Circuit Design","MATLAB","Power Systems"], linkedin: "https://www.linkedin.com/in/adityaverma80" }
];

module.exports = { data: users };
